Rails.application.routes.draw do
  root   'static_pages#top'
  post   '/login',  to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get    'users' , to: 'users#index', as: 'users'
  delete 'users/:id' , to: 'users#destroy', as: 'user_delete'
  get    'users/new' , to: 'users#new'
  post   'users/new' , to: 'users#new', as: 'user_new'
  get    'users/:id/edit' , to: 'users#edit', as: 'users_edit'
  post   'users/edit' , to: 'users#edit', as: 'user_edit'
  get    'users/confirm' , to: 'users#confirm'
  post   'users/confirm' , to: 'users#confirm', as: 'user_confirm'
  get    'users/:id/detail' , to: 'users#detail', as: 'user_detail'
  get    'users/search' , to: 'users#search'
  post   'users/search',  to: 'users#search', as: 'user_search'
end
