# 代表
User.create!(employee_number:       99999999,
             password:              "password",
             password_confirmation: "password",
             name:                  "代表",
             nearest_station:       "東京駅",
             telephone_number:      "012-3456-7890",
             join_able_date:        nil,
             admin_flag:            true)

# 第一号
User.create!(employee_number:       11111111,
             password:              "password",
             password_confirmation: "password",
             name:                  "樋口健児",
             nearest_station:       "練馬駅",
             telephone_number:      "090-5496-0563",
             join_able_date:        "2020-04-01",
             admin_flag:            false)